import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { prisma } from "@/lib/prisma";
import { generateMealPlan } from "@/lib/mealPlanGenerator";
import {
  AiRecommendationError,
  buildRecommendRequest,
  isEmptyRecommendationError,
  isMealFallbackEnabled,
  type NormalizedMealRecommendationResult,
  requestAiMealRecommendation,
} from "@/lib/ai/recommendationClient";

export const runtime = "nodejs";
export const maxDuration = 120;

function normalizeFallbackItems(
  items: Awaited<ReturnType<typeof generateMealPlan>>,
): NormalizedMealRecommendationResult {
  const meals = ["BREAKFAST", "LUNCH", "DINNER", "SNACK"];

  return {
    source: "fallback",
    dailyPlan: meals.map((mealName) => {
      const recommendations = items
        .filter((item) => item.dayNumber === 1 && item.mealType === mealName)
        .map((item) => ({
          foodName: item.foodName,
          idealGrams: item.servingG,
          idealCalories: item.calories,
          idealProtein: item.proteinG,
          idealFat: item.fatG,
          idealCarb: item.carbsG,
        }));

      return {
        mealName,
        targetCalories: recommendations.reduce(
          (total, item) => total + (item.idealCalories ?? 0),
          0,
        ),
        recommendations,
      };
    }),
    narrativeSummary:
      "Generated by the local fallback meal planner because AI recommendation was unavailable.",
  };
}

export async function POST() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const profile = await prisma.userProfile.findUnique({
      where: { userId: user.id },
      include: {
        allergies: {
          include: {
            allergen: true,
          },
        },
      },
    });

    if (!profile || !profile.targetCalories) {
      return NextResponse.json(
        {
          error: "Profil belum lengkap. Silakan isi data fisik terlebih dahulu.",
        },
        { status: 400 },
      );
    }

    try {
      const { requestBody } = buildRecommendRequest(profile);
      const result = await requestAiMealRecommendation(requestBody);

      return NextResponse.json(result);
    } catch (error) {
      if (!isMealFallbackEnabled() && !isEmptyRecommendationError(error)) {
        const errorMessage =
          error instanceof AiRecommendationError
            ? error.message
            : "AI recommendation service is unavailable.";

        return NextResponse.json(
          {
            error:
              "AI recommendation service is currently unavailable. Please try again later.",
            detail: errorMessage,
            source: "ai",
          },
          {
            status:
              error instanceof AiRecommendationError && error.status === 422
                ? 422
                : 503,
          },
        );
      }

      const fallbackItems = await generateMealPlan(
        user.id,
        profile.targetCalories,
        profile.allergies.map((allergy) => allergy.allergenId),
      );

      return NextResponse.json(normalizeFallbackItems(fallbackItems));
    }
  } catch (error) {
    console.error("POST /api/meal-recommendation error:", error);
    return NextResponse.json(
      { error: "Terjadi kesalahan server" },
      { status: 500 },
    );
  }
}
