import { MealType } from "@prisma/client";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { prisma } from "@/lib/prisma";
import { generateMealPlan } from "@/lib/mealPlanGenerator";
import {
  AiRecommendationError,
  buildRecommendRequest,
  isMealFallbackEnabled,
  type NormalizedMealRecommendationResult,
  requestAiMealRecommendation,
} from "@/lib/ai/recommendationClient";

function normalizeMealType(mealName: string): MealType {
  const normalized = mealName.toLowerCase();

  if (normalized.includes("breakfast") || normalized.includes("sarapan")) {
    return "BREAKFAST";
  }
  if (normalized.includes("lunch") || normalized.includes("siang")) {
    return "LUNCH";
  }
  if (normalized.includes("dinner") || normalized.includes("malam")) {
    return "DINNER";
  }
  if (normalized.includes("snack") || normalized.includes("cemilan")) {
    return "SNACK";
  }

  return "SNACK";
}

async function saveAiMealPlan({
  userId,
  targetCalories,
  result,
}: {
  userId: string;
  targetCalories: number;
  result: NormalizedMealRecommendationResult;
}) {
  const startDate = new Date();
  const endDate = new Date();
  endDate.setDate(endDate.getDate() + 6);

  const savedPlan = await prisma.$transaction(async (tx) => {
    const plan = await tx.mealPlan.create({
      data: {
        userId,
        startDate,
        endDate,
        targetCalories,
        source: result.source,
        narrativeSummary: result.narrativeSummary,
      },
    });

    for (const meal of result.dailyPlan) {
      const mealType = normalizeMealType(meal.mealName);

      for (const recommendation of meal.recommendations) {
        const caloriesPer100g = recommendation.calories100g ?? 0;
        const idealGrams = recommendation.idealGrams ?? 100;
        const idealCalories = recommendation.idealCalories ?? 0;

        const food = await tx.food.upsert({
          where: { name: recommendation.foodName },
          update: {
            caloriesPer100g,
          },
          create: {
            name: recommendation.foodName,
            category: "AI Recommendation",
            caloriesPer100g,
            proteinPer100g: 0,
            carbsPer100g: 0,
            fatPer100g: 0,
          },
        });

        await tx.mealPlanItem.create({
          data: {
            mealPlanId: plan.id,
            foodId: food.id,
            dayNumber: 1,
            mealType,
            servingG: idealGrams,
            calories: idealCalories,
            proteinG: 0,
            carbsG: 0,
            fatG: 0,
            caloriesPer100g,
            matchScore: recommendation.matchScore,
          },
        });
      }
    }

    return plan;
  });

  return { savedPlan, startDate, endDate };
}

async function saveFallbackMealPlan({
  userId,
  targetCalories,
  allergenIds,
}: {
  userId: string;
  targetCalories: number;
  allergenIds: string[];
}) {
  const generatedItems = await generateMealPlan(
    userId,
    targetCalories,
    allergenIds,
  );
  const startDate = new Date();
  const endDate = new Date();
  endDate.setDate(endDate.getDate() + 6);

  const savedPlan = await prisma.$transaction(async (tx) => {
    const plan = await tx.mealPlan.create({
      data: {
        userId,
        startDate,
        endDate,
        targetCalories,
        source: "fallback",
        narrativeSummary:
          "Generated by the local fallback meal planner because AI recommendation was unavailable.",
      },
    });

    await tx.mealPlanItem.createMany({
      data: generatedItems.map((item) => ({
        mealPlanId: plan.id,
        foodId: item.foodId,
        dayNumber: item.dayNumber,
        mealType: item.mealType,
        servingG: item.servingG,
        calories: item.calories,
        proteinG: item.proteinG,
        carbsG: item.carbsG,
        fatG: item.fatG,
      })),
    });

    return plan;
  });

  return { savedPlan, startDate, endDate, totalFoodsGenerated: generatedItems.length };
}

export async function GET() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const mealPlan = await prisma.mealPlan.findFirst({
      where: { userId: user.id },
      orderBy: { createdAt: "desc" },
      include: {
        items: {
          include: {
            food: true,
          },
          orderBy: [{ dayNumber: "asc" }, { mealType: "asc" }],
        },
      },
    });

    if (!mealPlan) {
      return NextResponse.json(
        { error: "Meal plan belum dibuat", hasMealPlan: false },
        { status: 404 },
      );
    }

    const maxDay = Math.max(1, ...mealPlan.items.map((item) => item.dayNumber));
    const days = Array.from({ length: maxDay }, (_, i) => {
      const dayNumber = i + 1;
      const dayItems = mealPlan.items.filter(
        (item) => item.dayNumber === dayNumber,
      );

      const totalCalories = dayItems.reduce((sum, item) => sum + item.calories, 0);
      const totalProteinG = dayItems.reduce((sum, item) => sum + item.proteinG, 0);
      const totalCarbsG = dayItems.reduce((sum, item) => sum + item.carbsG, 0);
      const totalFatG = dayItems.reduce((sum, item) => sum + item.fatG, 0);

      return {
        dayNumber,
        totalCalories: Math.round(totalCalories),
        totalProteinG: Math.round(totalProteinG * 10) / 10,
        totalCarbsG: Math.round(totalCarbsG * 10) / 10,
        totalFatG: Math.round(totalFatG * 10) / 10,
        meals: {
          BREAKFAST: dayItems.filter((item) => item.mealType === "BREAKFAST"),
          LUNCH: dayItems.filter((item) => item.mealType === "LUNCH"),
          DINNER: dayItems.filter((item) => item.mealType === "DINNER"),
          SNACK: dayItems.filter((item) => item.mealType === "SNACK"),
        },
      };
    });

    return NextResponse.json({
      hasMealPlan: true,
      mealPlan: {
        id: mealPlan.id,
        source: mealPlan.source,
        narrativeSummary: mealPlan.narrativeSummary,
        startDate: mealPlan.startDate,
        endDate: mealPlan.endDate,
        targetCalories: mealPlan.targetCalories,
        createdAt: mealPlan.createdAt,
        days,
      },
    });
  } catch (error) {
    console.error("GET /api/meal-plan error:", error);
    return NextResponse.json(
      { error: "Terjadi kesalahan server" },
      { status: 500 },
    );
  }
}

export async function POST() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const profile = await prisma.userProfile.findUnique({
      where: { userId: user.id },
      include: {
        allergies: {
          include: {
            allergen: true,
          },
        },
      },
    });

    if (!profile || !profile.targetCalories) {
      return NextResponse.json(
        {
          error: "Profil belum lengkap. Silakan isi data fisik terlebih dahulu.",
        },
        { status: 400 },
      );
    }

    const allergenIds = profile.allergies.map((allergy) => allergy.allergenId);
    let source: "ai" | "fallback" = "ai";
    let warning: string | undefined;

    try {
      const aiResult = await requestAiMealRecommendation(
        buildRecommendRequest(profile),
      );
      const { savedPlan, startDate, endDate } = await saveAiMealPlan({
        userId: user.id,
        targetCalories: profile.targetCalories,
        result: aiResult,
      });

      return NextResponse.json(
        {
          message: "AI meal recommendation berhasil dibuat!",
          source: "ai",
          mealPlanId: savedPlan.id,
          narrativeSummary: aiResult.narrativeSummary,
          summary: {
            targetCaloriesPerDay: profile.targetCalories,
            totalFoodsGenerated: aiResult.dailyPlan.reduce(
              (total, meal) => total + meal.recommendations.length,
              0,
            ),
            startDate: startDate.toISOString().split("T")[0],
            endDate: endDate.toISOString().split("T")[0],
            allergenFiltered: allergenIds.length,
          },
        },
        { status: 201 },
      );
    } catch (error) {
      if (!isMealFallbackEnabled()) {
        const errorMessage =
          error instanceof AiRecommendationError
            ? error.message
            : "AI recommendation service is unavailable.";

        return NextResponse.json(
          {
            error:
              "AI recommendation service is currently unavailable. Please try again later.",
            detail: errorMessage,
            source: "ai",
          },
          {
            status:
              error instanceof AiRecommendationError && error.status === 422
                ? 422
                : 503,
          },
        );
      }

      source = "fallback";
      warning =
        error instanceof Error
          ? error.message
          : "AI recommendation failed. Local fallback was used.";
    }

    const fallback = await saveFallbackMealPlan({
      userId: user.id,
      targetCalories: profile.targetCalories,
      allergenIds,
    });

    return NextResponse.json(
      {
        message: "Meal plan dibuat menggunakan fallback lokal.",
        source,
        warning,
        mealPlanId: fallback.savedPlan.id,
        summary: {
          targetCaloriesPerDay: profile.targetCalories,
          totalFoodsGenerated: fallback.totalFoodsGenerated,
          startDate: fallback.startDate.toISOString().split("T")[0],
          endDate: fallback.endDate.toISOString().split("T")[0],
          allergenFiltered: allergenIds.length,
        },
      },
      { status: 201 },
    );
  } catch (error: unknown) {
    console.error("POST /api/meal-plan error:", error);

    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json(
      { error: "Terjadi kesalahan server" },
      { status: 500 },
    );
  }
}
